FROM node:16.13.0-alpine3.13 as build
WORKDIR /home/hello-world
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.21.3-alpine
COPY --from=build /home/hello-world/build /usr/share/nginx/html