version: "3"
services:
  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./src:/home/hello-world/src:ro
    ports:
      - "3000:3000"
    env_file:
      - ./.env